name: flutter_async_builder
description: Convenience Widgets for Future and Stream Builder
version: 0.0.2+1
homepage: https://github.com/Johann13/flutter_async_builder

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
