name: flutter_async_builder
description: Convenience Widgets for Future and Stream Builder
version: 0.1.0-nullsafety
homepage: https://github.com/Johann13/flutter_async_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
